### ISSUE TITLE
Proposal: Use a contructor template

### ISSUE THREAD

**Issue by DSchroer** [bschwind/opencascade-rs#15]
I know in the past you have opted against using templates on the C++ side. However I was browsing the `cxx` thread regarding constructors and one of the recent posts recommended a workaround to the problem. Rather than instrument each constructor by itself, create a template like so:
```
template<typename T, typename... Args>
std::unique_ptr<T> construct(Args... args)
{
  return std::unique_ptr(new T(args...));
}
```

Then we can just re-use it when binding a new constructor.

What are your thoughts on taking this approach to remove some of the boilerplate?

Original thread:
https://github.com/dtolnay/cxx/issues/280#issuecomment-1344153115

**Comment by bschwind** [comment]
Oh this is nice, I would definitely be in favor of adding this if it reduces boilerplate and doesn't introduce too much complexity.
