### ISSUE TITLE
Have you tried autocxx? 

### ISSUE THREAD

**Issue by DSchroer** [bschwind/opencascade-rs#8]
I was playing with some tools. I think we can do better than the manual cxx bindings. 
https://google.github.io/autocxx/

lib.rs
```
autocxx::include_cpp! {
    #include "gp_Pnt.hxx"
    generate!("gp_Pnt")
}

pub use ffi::*;
```

lib_test.rs
```
use opencascade_sys::{gp_Pnt};
use autocxx::prelude::*;

#[test]
fn test_gp_Pnt() {
    unsafe {
        moveit! { let mut pt = gp_Pnt::new2(1.0, 2.0, 3.0) };
        assert_eq!(1.0, pt.X());
        assert_eq!(2.0, pt.Y());
        assert_eq!(3.0, pt.Z());
    }
}
```

**Comment by bschwind** [comment]
Interesting! I forgot this crate existed, thanks for bringing it to my attention.

I'll try to play around with it this weekend and see what kind of code it generates. I always hesitate to add another layer of abstraction on top of things, but this one will probably be worth it.

**Comment by DSchroer** [comment]
Nevermind. I wasted too much time on it today. Most of what you get is garbage and its a pain to reconcile. I think this project is better on the current path.

**Comment by bschwind** [comment]
Oh, that's a shame. I think over time the main `cxx` crate will improve and make things not too bad overall, especially once we can generate constructors automatically.

There are a lot of extra constructors and such in the C++ code that we probably won't even need, so adding them a la carte when we need them is probably okay for now.
