### ISSUE TITLE
Add some caching to CI

### ISSUE THREAD

**Issue by bschwind** [bschwind/opencascade-rs#80]
While the initial build of opencascade is quite heavy, iterative builds are relatively fast so our CI will benefit greatly from caching the `target/` directory.

**Comment by strohel** [comment]
Oh yeah I also thought we should do this. Let me take this, should hopefully be straighforward.

**Comment by bschwind** [comment]
With `occt-sys` published to crates.io, build times are significantly faster. We could also switch to dynamic linking (done in #87) to make things even faster if we desire.
