### ISSUE TITLE
Runtime performance is significantly slower after occt-sys extraction

### ISSUE THREAD

**Issue by bschwind** [bschwind/opencascade-rs#95]
Not sure if this is due to bad linking optimization or cmake accidentally being in debug mode, but I'm seeing much slower run times for the `keycap` example between these two commits:

769cf3985b8f2af1c09db429ea193f6d93fbfc44

to

f82feb36adecfa9ad42dbd10af0b5c10c37622d7

### Before (commit 769cf3985b8f2af1c09db429ea193f6d93fbfc44)
```
brian opencascade-rs $ cargo run --release --example keycap
   Compiling opencascade-sys v0.1.0 (/Users/brian/projects/opencascade-rs/crates/opencascade-sys)
   Compiling opencascade v0.1.0 (/Users/brian/projects/opencascade-rs/crates/opencascade)
    Finished release [optimized] target(s) in 4m 43s
     Running `target/release/examples/keycap`
[crates/opencascade/examples/keycap.rs:252] start.elapsed() = 2.001305167s
brian opencascade-rs $ cargo run --release --example keycap
    Finished release [optimized] target(s) in 0.14s
     Running `target/release/examples/keycap`
[crates/opencascade/examples/keycap.rs:252] start.elapsed() = 1.994357834s
brian opencascade-rs $ cargo run --release --example keycap
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/examples/keycap`
[crates/opencascade/examples/keycap.rs:252] start.elapsed() = 1.989243625s
brian opencascade-rs $ cargo run --release --example keycap
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/examples/keycap`
[crates/opencascade/examples/keycap.rs:252] start.elapsed() = 2.003615459s
```

### After (commit f82feb36adecfa9ad42dbd10af0b5c10c37622d7)

```
brian opencascade-rs $ cargo run --release --example keycap
    Blocking waiting for file lock on build directory
   Compiling opencascade v0.1.0 (/Users/brian/projects/opencascade-rs/crates/opencascade)
    Finished release [optimized] target(s) in 4m 08s
     Running `target/release/examples/keycap`
[crates/opencascade/examples/keycap.rs:252] start.elapsed() = 11.370032792s
brian opencascade-rs $ cargo run --release --example keycap
    Finished release [optimized] target(s) in 0.57s
     Running `target/release/examples/keycap`
[crates/opencascade/examples/keycap.rs:252] start.elapsed() = 10.897455208s
```

**Comment by strohel** [comment]
Interesting, let me have a look. I hoped the change would produce almost bit-by-bit equal binaries.

**Comment by strohel** [comment]
Okay I've found the culprit, OCCT is built in debug mode also in release builds (shortened output):
``strohel@thicky ~/work/opencascade-rs $ cargo build --release --example keycap -vv``
``   Compiling occt-sys v0.1.0 (/home/strohel/work/opencascade-rs/crates/occt-sys)``
``     Running `/home/strohel/work/opencascade-rs/target/release/build/occt-sys-cbea783228109043/build-script-build` ``
``[occt-sys 0.1.0] running: cd "/home/strohel/work/opencascade-rs/target/release/build/occt-sys-c676c8555b5ded36/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/strohel/work/opencascade-rs/crates/occt-sys/OCCT" "-DBUILD_LIBRARY_TYPE=Static" "-DBUILD_MODULE_Draw=FALSE" "-DUSE_OPENGL=FALSE" "-DUSE_GLES2=FALSE" "-DUSE_D3D=FALSE" "-DUSE_VTK=FALSE" "-DUSE_TCL=FALSE" "-DUSE_XLIB=FALSE" "-DUSE_FREETYPE=FALSE" "-DUSE_FREEIMAGE=FALSE" "-DUSE_OPENVR=FALSE" "-DUSE_FFMPEG=FALSE" "-DINSTALL_DIR_LIB=lib" "-DINSTALL_DIR_INCLUDE=include" "-DCMAKE_INSTALL_PREFIX=/home/strohel/work/opencascade-rs/target/release/build/occt-sys-c676c8555b5ded36/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=``**``Debug"``**
```

Now to find out why.

**Comment by bschwind** [comment]
Aha! I had a sneaking suspicion CMake was getting into debug builds and had specified that release flag in one of my PRs because I didn't completely trust it.

That's reassuring it's a simple problem and not something trickier like separate compilation units that give fewer opportunities for optimization.
